version: "3"

networks:
  network:
    driver: bridge


services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    networks:
      - network


  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    #    restart: always
    networks:
      - network
