version: "3"

networks:
  network:
    driver: bridge


services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5433:5432"
    networks:
      - network


  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    #    restart: always
    networks:
      - network
