"""add receiver to joint payments

Revision ID: 6ad51bea90cb
Revises: a1b2c3d4e5f6
Create Date: 2026-03-05 21:32:26.715691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ad51bea90cb'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jointpayment', sa.Column('receiver_character_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jointpayment', 'character', ['receiver_character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jointpayment', type_='foreignkey')
    op.drop_column('jointpayment', 'receiver_character_id')
    # ### end Alembic commands ###
